name: MYCI
on: [push]
jobs:
  job1:
    ## 运行环境
    runs-on: ubuntu-latest
    container:
      image: node:8
    services:
      nginx:
        image: nginx
        ports:
          - 8080:80
        env:
          NGINX_PORT: 80
    ## 运行步骤
    steps:
    ## 下载github仓库的执行流程。 actions-用户， checkout-仓库
    ## uses语法 {owner}/{repo}@{ref}
    - uses: actions/checkout@v1
    ## 运行shell指令
    - run: |
        echo hello
        curl localhost:8080
