name: MYCI
on: [push]
jobs:
  job1:
    ## 运行环境
    runs-on: ubuntu-latest
    container:
      image: node:8
    ## 运行步骤
    steps:
    ## 下载github仓库的执行流程。 actions-用户， checkout-仓库
    ## uses语法 {owner}/{repo}@{ref}
    - uses: actions/checkout@v1
    ## 运行shell指令
    - run: echo hello
    - run: node -v
